insert into link (id, name, href, category_id) values (1, 'Frangula purshiana (DC.) A. Gray', '#', 2);
insert into link (id, name, href, category_id) values (2, 'Oplismenus hirtellus (L.) P. Beauv. ssp. undulatifolius (Ard.) U. Scholz', '#', 3);
insert into link (id, name, href, category_id) values (3, 'Agave decipiens Baker', '#', 3);
insert into link (id, name, href, category_id) values (4, 'Eriogonum latifolium Sm.', '#', 2);
insert into link (id, name, href, category_id) values (5, 'Asclepias quinquedentata A. Gray', '#', 2);
insert into link (id, name, href, category_id) values (6, 'Bryoerythrophyllum Chen', '#', 2);
insert into link (id, name, href, category_id) values (7, 'Ptelea trifoliata L. ssp. trifoliata var. mollis Torr. & A. Gray', '#', 2);
insert into link (id, name, href, category_id) values (8, 'Oenothera elata Kunth', '#', 3);
insert into link (id, name, href, category_id) values (9, 'Vulpia octoflora (Walter) Rydb. var. glauca (Nutt.) Fernald', '#', 1);
insert into link (id, name, href, category_id) values (10, 'Hieracium scabrum Michx. var. tonsum Fernald & H. St. John', '#', 2);
insert into link (id, name, href, category_id) values (11, 'Brachypodium distachyon (L.) P. Beauv.', '#', 2);
insert into link (id, name, href, category_id) values (12, 'Potentilla arguta Pursh ssp. convallaria (Rydb.) D.D. Keck', '#', 1);
insert into link (id, name, href, category_id) values (13, 'Caloplaca intermedia (de Lesd.) Zahlbr.', '#', 3);
insert into link (id, name, href, category_id) values (14, 'Nassella viridula (Trin.) Barkworth', '#', 1);
insert into link (id, name, href, category_id) values (15, 'Crataegus mendosa Beadle', '#', 2);
insert into link (id, name, href, category_id) values (16, 'Poitea florida (Vahl) Lavin', '#', 3);
insert into link (id, name, href, category_id) values (17, 'Lycurus setosus (Nutt.) C.G. Reeder', '#', 3);
insert into link (id, name, href, category_id) values (18, 'Lupinus sericatus Kellogg', '#', 2);
insert into link (id, name, href, category_id) values (19, 'Thelotrema santense Tuck.', '#', 3);
insert into link (id, name, href, category_id) values (20, 'Epidendrum jamaicense Lindl.', '#', 2);