insert into link (id, name, href, category_id) values (1, 'Selaginella ludoviciana A. Braun', '#', 4);
insert into link (id, name, href, category_id) values (2, 'Orthotrichum striatum Hedw.', '#', 7);
insert into link (id, name, href, category_id) values (3, 'Poa nemoralis L. ssp. nemoralis', '#', 7);
insert into link (id, name, href, category_id) values (4, 'Lecidea steineri Hertel', '#', 5);
insert into link (id, name, href, category_id) values (5, 'Lobelia puberula Michx. var. puberula', '#', 6);
insert into link (id, name, href, category_id) values (6, 'Salvinia molesta Mitchell', '#', 4);
insert into link (id, name, href, category_id) values (7, 'Atriplex spinifera J.F. Macbr.', '#', 2);
insert into link (id, name, href, category_id) values (8, 'Cochleanthes flabelliformis (Sw.) R.E. Schult. & Garay', '#', 5);
insert into link (id, name, href, category_id) values (9, 'Tradescantia bracteata Small', '#', 6);
insert into link (id, name, href, category_id) values (10, 'Oxytropis lambertii Pursh var. bigelovii A. Gray', '#', 7);
insert into link (id, name, href, category_id) values (11, 'Eutrochium purpureum (L.) E.E. Lamont var. carolinianum Sorrie', '#', 1);
insert into link (id, name, href, category_id) values (12, 'Melilotus Mill.', '#', 4);
insert into link (id, name, href, category_id) values (13, 'Xanthopsorella Kalb & Hafellner', '#', 5);
insert into link (id, name, href, category_id) values (14, 'Napaea dioica L.', '#', 1);
insert into link (id, name, href, category_id) values (15, 'Eriophorum russeolum Fr. ex Hartm. var. albidum F. Nyl.', '#', 3);
insert into link (id, name, href, category_id) values (16, 'Cylindropuntia versicolor (Engelm. ex J.M. Coult.) F.M. Knuth', '#', 7);
insert into link (id, name, href, category_id) values (17, 'Scaevola sericea Vahl', '#', 3);
insert into link (id, name, href, category_id) values (18, 'Trifolium depauperatum Desv. var. diversifolium (Nutt.) McDermott', '#', 5);
insert into link (id, name, href, category_id) values (19, 'Cymopterus rosei (M.E. Jones ex J.M. Coult. & Rose) M.E. Jones', '#', 8);
insert into link (id, name, href, category_id) values (20, 'Euphrasia subarctica Raup', '#', 4);
insert into link (id, name, href, category_id) values (21, 'Allium tolmiei (Hook.) Baker ex S. Watson var. tolmiei', '#', 3);
insert into link (id, name, href, category_id) values (22, 'Cheilanthes notholaenoides (Desv.) Maxon ex Weath.', '#', 4);
insert into link (id, name, href, category_id) values (23, 'Carex viridistellata Derieg, Reznicek, & Bruederle', '#', 6);
insert into link (id, name, href, category_id) values (24, 'Moehringia L.', '#', 2);
insert into link (id, name, href, category_id) values (25, 'Oemleria cerasiformis (Torr. & A. Gray ex Hook. & Arn.) Landon', '#', 6);
insert into link (id, name, href, category_id) values (26, 'Lupinus nanus Douglas ex Benth. ssp. latifolius (Benth. ex Torr.) D. Dunn', '#', 5);
insert into link (id, name, href, category_id) values (27, 'Clauzadea immersa (Hoffm.) Hafellner & Bellem.', '#', 7);
insert into link (id, name, href, category_id) values (28, 'Didymodon reedii H. Rob.', '#', 8);
insert into link (id, name, href, category_id) values (29, 'Amaranthus californicus (Moq.) S. Watson', '#', 5);
insert into link (id, name, href, category_id) values (30, 'Selaginella menziesii (Hook. & Grev.) Spring', '#', 4);
insert into link (id, name, href, category_id) values (31, 'Quercus sadleriana R. Br. ter', '#', 5);
insert into link (id, name, href, category_id) values (32, 'Guilleminea densa (Humb. & Bonpl. ex Schult.) Moq. var. aggregata Uline & Bray', '#', 2);
insert into link (id, name, href, category_id) values (33, 'Atriplex lindleyi Moq.', '#', 3);
insert into link (id, name, href, category_id) values (34, 'Zapoteca H.M. Hern.', '#', 5);
insert into link (id, name, href, category_id) values (35, 'Chlorophytum capense (L.) Voss', '#', 7);
insert into link (id, name, href, category_id) values (36, 'Erigeron argentatus A. Gray', '#', 4);
insert into link (id, name, href, category_id) values (37, 'Mercurialis L.', '#', 1);
insert into link (id, name, href, category_id) values (38, 'Lecythis ollaria Loefl.', '#', 4);
insert into link (id, name, href, category_id) values (39, 'Clematis columbiana (Nutt.) Torr. & A. Gray var. columbiana', '#', 3);
insert into link (id, name, href, category_id) values (40, 'Gaillardia pulchella Foug. var. australis Turner & M.A. Whalen', '#', 6);
insert into link (id, name, href, category_id) values (41, 'Castilleja ambigua Hook. & Arn. var. meadii J.M.Egger & Ruygt', '#', 5);
insert into link (id, name, href, category_id) values (42, 'Stipa klemenzii Roshev.', '#', 1);
insert into link (id, name, href, category_id) values (43, 'Lupinus densiflorus Benth. var. lacteus (Kellogg) C.P. Sm.', '#', 1);
insert into link (id, name, href, category_id) values (44, 'Lespedeza ×neglecta Mack. & Bush (pro sp.)', '#', 6);
insert into link (id, name, href, category_id) values (45, 'Dysphania botrys (L.) Mosyakin & Clemants', '#', 7);
insert into link (id, name, href, category_id) values (46, 'Hypericum edisonianum (Small) P. Adams & N. Robson', '#', 5);
insert into link (id, name, href, category_id) values (47, 'Gochnatia Kunth', '#', 5);
insert into link (id, name, href, category_id) values (48, 'Senecio clarkianus A. Gray', '#', 1);
insert into link (id, name, href, category_id) values (49, 'Micranthemum glomeratum (Chapm.) Shinners', '#', 5);
insert into link (id, name, href, category_id) values (50, 'Valeriana edulis Nutt. ex Torr. & A. Gray var. ciliata (Torr. & A. Gray) Cronquist', '#', 4);
insert into link (id, name, href, category_id) values (51, 'Ludwigia bonariensis (Micheli) H. Hara', '#', 7);
insert into link (id, name, href, category_id) values (52, 'Festuca rubra L. ssp. mediana (Pavlick) Pavlick', '#', 2);
insert into link (id, name, href, category_id) values (53, 'Betula pumila L. var. renifolia Fernald', '#', 3);
insert into link (id, name, href, category_id) values (54, 'Solidago simplex Kunth ssp. randii (Porter) Ringius var. monticola (Porter) Ringius', '#', 1);
insert into link (id, name, href, category_id) values (55, 'Parthenocissus vitacea (Knerr) Hitchc.', '#', 5);
insert into link (id, name, href, category_id) values (56, 'Alectoria ochroleuca (Hoffm.) A. Massal.', '#', 7);
insert into link (id, name, href, category_id) values (57, 'Cochlidium rostratum (Hook.) Maxon ex C. Chr.', '#', 4);
insert into link (id, name, href, category_id) values (58, 'Hedeoma nana (Torr.) Briq. ssp. nana', '#', 5);
insert into link (id, name, href, category_id) values (59, 'Vancouveria planipetala Calloni', '#', 3);
insert into link (id, name, href, category_id) values (60, 'Scabiosa L.', '#', 6);
insert into link (id, name, href, category_id) values (61, 'Enemion stipitatum (A. Gray) J.R. Drumm. & Hutch.', '#', 7);
insert into link (id, name, href, category_id) values (62, 'Bellardia trixago (L.) All.', '#', 2);
insert into link (id, name, href, category_id) values (63, 'Carex vulpinoidea Michx.', '#', 4);
insert into link (id, name, href, category_id) values (64, 'Bromus lanatipes (Shear) Rydb.', '#', 8);
insert into link (id, name, href, category_id) values (65, 'Echinoplaca pellucida (Müll. Arg.) R. Sant.', '#', 7);
insert into link (id, name, href, category_id) values (66, 'Mertensia paniculata (Aiton) G. Don var. alaskana (Britton) L.O. Williams', '#', 4);
insert into link (id, name, href, category_id) values (67, 'Cerastium beeringianum Cham. & Schltdl. ssp. beeringianum', '#', 5);
insert into link (id, name, href, category_id) values (68, 'Machaeranthera coloradoensis (A. Gray) Osterh. var. brandegeei (Rydb.) T.J. Watson ex R.L. Hartm.', '#', 4);
insert into link (id, name, href, category_id) values (69, 'Errazurizia rotundata (Wooton) Barneby', '#', 2);
insert into link (id, name, href, category_id) values (70, 'Hordeum murinum L. ssp. glaucum (Steud.) Tzvelev', '#', 3);
